ERROR:pymodbus.client.sync:Port must be configured before it can be used.
ERROR:RaspPiReader.libs.communication:Failed to connect to MODBUS RTU device on port None
ERROR:RaspPiReader.libs.communication:Invalid register read type: None
ERROR:pymodbus.client.sync:Port must be configured before it can be used.
ERROR:RaspPiReader.libs.communication:Exception during coil read: Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[9600])]
Traceback (most recent call last):
  File "C:\Users\tavsh\Desktop\26022025\src1-main\RaspPiReader\libs\communication.py", line 113, in read_bool_addresses
    result = self.client.read_coils(addr, count, unit=dev)
  File "C:\Users\tavsh\Downloads\src1-main (1)\new13022025\src1-main\.venv\lib\site-packages\pymodbus\client\common.py", line 48, in read_coils
    return self.execute(request)
  File "C:\Users\tavsh\Downloads\src1-main (1)\new13022025\src1-main\.venv\lib\site-packages\pymodbus\client\sync.py", line 108, in execute
    raise ConnectionException("Failed to connect[%s]" % (self.__str__()))
pymodbus.exceptions.ConnectionException: Modbus Error: [Connection] Failed to connect[ModbusSerialClient(rtu baud[9600])]
